---
- name: "Download Logstash's rpm"
  when: ansible_facts.virtualization_type != "docker"
  include: rpm.yml

- name: Install Logstash tar.gz (on Docker)
  when: ( ansible_connection == "community.docker.docker" )
        or ( ansible_facts.env.container == "podman" )
        or ( ansible_facts.virtualization_type == "docker" )
  include: targz.yml
